name: Unify spells and deploy site
on:
  push:
    branches:
      - "main"
    paths:
      - "spells/*.json"
      - "index.html"
  schedule:
    - cron: "0 5 1 * *"  # 05:00 UTC, 1st day of every month
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Unify spell files
        run: |
          python spells/unify_spell_files.py

      - name: Commit and push spells.json
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: 'GH commit: Update spells.json with new spells'
          add: 'spells.json'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./
          retention-days: 32

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
