name: Creation of 'spells.json'
on:
  push:
    branches:
      - "**"
permissions:
  contents: write
jobs:
  unify:
    runs-on: ubuntu-latest
    steps:
      -   uses: actions/checkout@v3
      -   name: Set up Python 3.12
          uses: actions/setup-python@v4
          with:
            python-version: 3.12
      -   name: Spells files unification
          run: python spells/unify_spell_files.py
