name: Creation of 'spells.json'
on:
  push:
    branches:
      - "main"
      - "html_table"
  workflow_dispatch:  # This will also run when called manually.

permissions:
  contents: write
jobs:
  unify:
    runs-on: ubuntu-latest

    steps:
      # 1: Cloning repo with credentials to allow a 'push commit'
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      # 2: Configure python.
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      # 3: Execute script.
      - name: Unify spell files
        run: |
          python spells/unify_spell_files.py

      # 4: Add commit and push.
      - name: Commit and push spells.json
        uses: EndBug/add-and-commit@v9
        with:
          # Usa el GitHub Token disponible en ${{ secrets.GITHUB_TOKEN }}
          author_name: GitHub Actions
          author_email: actions@github.com
          message: 'GH commit: Update spells.json with new spells'
          add: 'spells.json'

      # 5: Configure & deploy GH Pages
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: |
            spells.html
            spells.json

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
