name: Creation of 'spells.json'
on:
  push:
    branches:
      - "main"
      - "html_table"
  workflow_dispatch:  # This will also run when called manually.

permissions:
  contents: write
  

jobs:
  unify:
    runs-on: ubuntu-latest

    steps:
      # 1: Cloning repo with credentials to allow a 'push commit'
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      # 2: Configure python.
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      # 3: Execute script.
      - name: Unify spell files
        run: |
          python spells/unify_spell_files.py

      # 4: Add commit and push.
      - name: Commit and push spells.json
        uses: EndBug/add-and-commit@v9
        with:
          # Usa el GitHub Token disponible en ${{ secrets.GITHUB_TOKEN }}
          author_name: GitHub Actions
          author_email: actions@github.com
          message: 'GH commit: Update spells.json with new spells'
          add: 'spells.json'

  deploy:
    needs: unify
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
